src/Entity/Piste.php
<?php

namespace App\Entity;

use App\Repository\PisteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PisteRepository::class)]
class Piste
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $difficulte = null;

    #[ORM\Column]
    private ?bool $ouverture = null;


    #[ORM\Column]
    private ?bool $block = null;

    #[ORM\ManyToOne(inversedBy: 'pistes')]
    private ?StationSki $station = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fermeture_expectionelle = null;

    #[ORM\ManyToMany(targetEntity: Defis::class, mappedBy: 'piste')]
    private Collection $defis;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $horaire_ouverture = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $horaire_fermeture = null;

    public function __construct()
    {
        $this->defis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDifficulte(): ?string
    {
        return $this->difficulte;
    }

    public function setDifficulte(string $difficulte): self
    {
        $this->difficulte = $difficulte;

        return $this;
    }

    public function getOuverture(): ?bool
    {
        return $this->ouverture;
    }

    public function setOuverture(bool $ouverture): self
    {
        $this->ouverture = $ouverture;

        return $this;
    }


    public function getBlock(): ?bool

    {
        return $this->block;
    }

    public function setBlock(bool $block): self
    {
        $this->block = $block;

        return $this;
    }

    public function getStation(): ?StationSki
    {
        return $this->station;
    }

    public function setStation(?StationSki $station): self
    {
        $this->station = $station;

        return $this;
    }


    public function getFermetureExpectionelle(): ?string
    {
        return $this->fermeture_expectionelle;
    }

    public function setFermetureExpectionelle(?string $fermeture_expectionelle): self
    {
        $this->fermeture_expectionelle = $fermeture_expectionelle;
        return $this;
    }

    /**
     * @return Collection<int, Defis>
     */
    public function getDefis(): Collection
    {
        return $this->defis;
    }

    public function addDefi(Defis $defi): self
    {
        if (!$this->defis->contains($defi)) {
            $this->defis->add($defi);
            $defi->addPiste($this);
        }

        return $this;
    }

    public function removeDefi(Defis $defi): self
    {
        if ($this->defis->removeElement($defi)) {
            $defi->removePiste($this);
        }
        return $this;
    }


    const PISTE_STATUS_OPEN = 'open';
    const PISTE_STATUS_CLOSE = 'close';
    const PISTE_STATUS_OPEN_BLOCKED = 'open_blocked';
    const PISTE_STATUS_CLOSE_BLOCKED = 'close_blocked';

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $pisteStatus = self::PISTE_STATUS_CLOSE;

    public function getPisteStatus(): ?string
    {
        return $this->pisteStatus;
    }

    public function setPisteStatus(string $pisteStatus): self
    {
        return $this->pisteStatus = $pisteStatus;
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getHoraireOuverture(): ?\DateTimeInterface
    {
        return $this->horaire_ouverture;
    }

    public function setHoraireOuverture(\DateTimeInterface $horaire_ouverture): self
    {
        $this->horaire_ouverture = $horaire_ouverture;


        return $this;
    }


    public function isOpen(): bool
    {
        return $this->pisteStatus === self::PISTE_STATUS_OPEN || $this->pisteStatus === self::PISTE_STATUS_OPEN_BLOCKED;
    }

    public function isClose(): bool
    {
        return $this->pisteStatus === self::PISTE_STATUS_CLOSE || $this->pisteStatus === self::PISTE_STATUS_CLOSE_BLOCKED;
    }

    public function isBlocked(): bool
    {
        return $this->pisteStatus === self::PISTE_STATUS_OPEN_BLOCKED || $this->pisteStatus === self::PISTE_STATUS_CLOSE_BLOCKED;
    }


    public function getHoraireFermeture(): ?\DateTimeInterface
    {
        return $this->horaire_fermeture;
    }

    public function setHoraireFermeture(\DateTimeInterface $horaire_fermeture): self
    {
        $this->horaire_fermeture = $horaire_fermeture;

        return $this;
    }

}

templates/app/Sedit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AppController!{% endblock %}

{% block body %}
    <style>
        body {
            background-image: url('/assets/image/background.png');
            background-size: cover;
            background-repeat: no-repeat;

        }
        main{
            padding: 20px;
        }
        .navbar{
            padding: 15px 0;
            background: #03312E;
        }
        .navbar .logo a span{
            color: #F0F6F6;
            transition: all 0.3s ease;
        }
        fieldset{
            border: 2px solid #03312E;
            border-radius: 6px;
            padding: 10px 20px;
            background-color: white;
            width: 20%;
            font-size: 18px;

        }
        .formpiste{
            margin-left: 250px;

        }

        table{
            border: 2px solid #03312E;
            border-radius: 6px;
            padding: 10px 20px;
            margin-bottom: 20px;
            background-color: white;
        }
        th  {
            padding-right: 10px;
            padding-left: 10px;
        }
        td  {
            padding-right: 10px;
            padding-left: 10px;
        }
        section{
            padding: 0;
        }
        @media only screen and (max-width: 800px){
            table{

                padding: 5px 5px;

            }
            th  {
                padding-right: 2.5px;
                padding-left: 2.5px;
                font-size: 15px;
            }
            td  {
                padding-right: 2.5px;
                padding-left: 2.5px;
                font-size: 15px;
            }
            fieldset{

                width: 50%;
                font-size: 18px;

            }
            .formpiste{
                margin-left: 50px;

            }
        }

    </style>

    <header >
        <nav class="navbar" >
            <div class="max-width">
                <div class="logo">
                    <a href="#">Peak <span> </span><span>EXPLORER.</span></a>
                </div>
                <ul class="menu">
                    <li><a href="{{ path('app_index') }}" class="menu-btn">Acceuil</a></li>
                    <li><a href="{{ path('app_Domaine') }}" class="menu-btn">Domaine</a></li>
                    <li><a href="{{ path('app_login') }}" class="menu-btn">login</a></li>
                    <li><a href="{{ path('app_register') }}" class="menu-btn">Register</a></li>
                    <li><a href="{{ path('admin_domaine') }}" class="menu-btn">Admin</a></li>

                </ul>
                <div class="menu-btn">
                    <i class="fas fa-bars"></i>
                    <img src="public/assets/images/menu.png">
                </div>
            </div>
        </nav>
    </header>
    <br><br><br><br>
    <main>
    <h1>la Stations {{ station.name }}</h1>
    <p>
        Bienvenue sur la page d'édition de la station {{ station.name }}
        <br>Vous pourrez ici ajouter, modifier ou supprimer des stations de ski.
        et aussi ouvrir/fermé les stations de ski en fonction de l'heure actuelle.

    </p>
        <div>

            <img src="/uploads/{{ station.image }}" alt="image de la station" width="200" height="200">
            <h4>{{ station.description }}</h4>
            <p>{{ station.location }}</p>
             </div>

    <a href="{{ path ('app_stationskimodif', {id : station.id}) }}"><button> modifier la station</button></a>

    <a href="{{ path ('fadd_remotee', {id : station.id}) }}"><button> Ajouter des pistes ou des remontees</button></a>


    <h2> Piste : </h2>
    <table class="table">
    <thead>
    <tr>
        <th>Nom</th>
        <th>Difficulté</th>
        <th>Statut</th>
        <th>Horaire d'ouverture</th>
        <th>Horaire de fermeture</th>
        <th>fermeture expectionelle</th>
    </tr>
    </thead>
        <tbody>
        {% for pistes in piste %}
            <tr>
                <td>{{ pistes.name }}</td>
                <td>{{ pistes.difficulte }}</td>
                <td>{% if pistes.ouverture %} Ouverte {% else %} Fermée {% endif %}</td>
                <td>{{ pistes.horaireOuverture|date('H:i') }}</td>
                <td>{{ pistes.horaireFermeture|date('H:i') }}</td>
                <td>{{ pistes.fermetureexpectionelle }}</td>
                <td>
                    {% if form[pistes.id] is defined %}
                        {{ form_start(form[pistes.id]) }}
                        {{ form_label(form[pistes.id].block) }}
                        {{ form_widget(form[pistes.id].block) }}
                        <button type="submit">Enregistrer</button>
                        {{ form_end(form[pistes.id]) }}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <div class="formpiste">
    <h1>Pistes</h1>
    {{ form_start(form) }}
    <input type="submit" value="Enregistrer">
    {{ form_end(form) }}
    </div>
    <h2> Remontée : </h2>
<table class="table">
    <thead>
    <tr>
        <th>Nom</th>
        <th>Statut</th>
        <th>Horaire d'ouverture</th>
        <th>Horaire de fermeture</th>
    </tr>
    </thead>
    <tbody>
    {% for remonte in remontee %}
    <tr>
        <td>{{ remonte.name }}</td>
        <td>{% if remonte.open %} Ouverte {% else %} Fermée {% endif %}</td>
        <td>{{ remonte.opentime|date('H:i') }}</td>
        <td>{{ remonte.closetime|date('H:i') }}</td>


    </tr>
    {% endfor %}
    </tbody>
</table>
    <br>
<div>
    <form action="{{ path('update_remontee', {'id' : station.id} ) }}" method="post">

        <select name="status">
            <option value="close">Fermée</option>
            <option value="open">Ouverte</option>
        </select>
        <input type="checkbox" name="block" value="1">
        <label for="block">Bloquer l'automatisation</label>
        <button type="submit">Submit</button>
    </form>
    </div>
    </main>
{% endblock %}

templates/app/domaine.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AppController!{% endblock %}

{% block body %}
<style>
    body {
        background-image: url('/assets/image/background.png');
        background-size: cover;
        background-repeat: no-repeat;
    }
    a{
        text-decoration: none;
        color: black;
        background-color: #007bff;
        border-radius: 10px;
        padding: 10px;
        border: 2px solid black;
    }

    button{
        background-color: #007bff;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        font-family: sans-serif;
        cursor: pointer;
    }
    .global{
        display: flex;
        flex-direction: column;

    }
    .global > div a {
        width: 7.5%;
        text-align: center;
    }
    </style>
    <h1>les Domaines de skis</h1>
    <p>
        Bienvenue sur la page des domaines de skis

    </p>
    {% if admin == true %}
        <a href="{{ path('domaine_new') }}">Ajouter un domaine</a>
    {% endif %}
    <div class="global">
        {% for domaines in domaine  %}
        <div>
            <h3>{{ domaines.name }}</h3>
            <img src="/uploads/{{ domaines.image }}" alt="image de la station" width="200" height="200">
            <br>
            <a href="{{ path('app_edit',{'id': domaines.id}) }}">voir la station</a>
        </div>


    {% endfor %}
    </div>

{% endblock %}

templates/app/domaines.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AppController!{% endblock %}

{% block body %}
<style>
    body {
        background-image: url('/assets/image/background.png');
        background-size: cover;
        background-repeat: no-repeat;
    }
    .navbar{
        padding: 15px 0;
        background: #03312E;
    }
    .navbar .logo a span{
        color: #F0F6F6;
        transition: all 0.3s ease;
    }

    .global{
        display: flex;


    }
    .global > div a {
        width: 7.5%;
        text-align: center;
    }
    @media(max-width: 600px){

        .Domaine{
            width: 450px;
            height: 450px;

            border-radius: 5px;
            margin: 10px;
            margin-bottom: 40px;
            text-align: center;


        }
        .Domaine h3{
            font-size: 50px;
        }
        .Domaine img{
            width: 300px;
            height: 300px;
            margin-bottom: 10px;
        }
        .presentation{
            width: 100%;
            text-align: center;

            font-size: 20px;
            padding-top: 50px;
        }
    }
    </style>
    <header >
        <nav class="navbar" >
            <div class="max-width">
                <div class="logo">
                    <a href="#">Peak <span> </span><span>EXPLORER.</span></a>
                </div>
                <ul class="menu">
                    <li><a href="{{ path('app_index') }}" class="menu-btn">Acceuil</a></li>
                    <li><a href="{{ path('app_Domaine') }}" class="menu-btn">Domaine</a></li>
                    <li><a href="{{ path('app_login') }}" class="menu-btn">login</a></li>
                    <li><a href="{{ path('app_register') }}" class="menu-btn">Register</a></li>
                    <li><a href="{{ path('admin_domaine') }}" class="menu-btn">Admin</a></li>

                </ul>
                <div class="menu-btn">
                    <i class="fas fa-bars"></i>
                    <img src="public/assets/images/menu.png">
                </div>
            </div>
        </nav>
    </header>
    <br><br><br><br>
    <div class="presentation">
    <h1>les Domaines de skis</h1>
    <p>
        Bienvenue sur la page des domaines de skis

    </p>
    </div>
    {% if admin == true %}
        <a href="{{ path('domaine_new') }}">Ajouter un domaine</a>
    {% endif %}
    <div class="global">
        {% for domaines in domaine  %}
        <div class="Domaine">
            <h3>{{ domaines.name }}</h3>
            <img src="/uploads/{{ domaines.image }}" alt="image de la station" width="200" height="200">
            <br>
            <a href="{{ path('app_edit',{'id': domaines.id}) }}">voir les stations du domaine</a>
        </div>


    {% endfor %}
    </div>

{% endblock %}

templates/app/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AppController!{% endblock %}

{% block body %}
    <style>

        body {
            background-image: url('/assets/image/background.png');
            background-size: cover;
            background-repeat: no-repeat;

        }
      .acces{
          text-decoration: none;
          color: black;
          font-size: 18px;
          background-color: white;
          border: 1px solid black;
            border-radius: 5px;
          padding: 5px;
      }
        .navbar{
            padding: 15px 0;
            background: #03312E;
        }
        .navbar .logo a span{
            color: #F0F6F6;
            transition: all 0.3s ease;
        }

        button{

            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-family: sans-serif;
            cursor: pointer;
        }
        .global{
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            margin-bottom: 20px;
        }
        .Domaine img{
            width: 200px;
            height: 200px;
            margin-bottom: 10px;
        }
        .Domaine{
            width: 250px;
            height: 250px;

            border-radius: 5px;
            margin: 10px;
            text-align: center;


        }
        section{
            padding: 0;
        }

        @media(max-width: 600px){

            .Domaine{
                width: 450px;
                height: 450px;

                border-radius: 5px;
                margin: 10px;
                margin-bottom: 40px;
                text-align: center;


            }
            .Domaine h3{
                font-size: 50px;
            }
            .Domaine img{
                width: 300px;
                height: 300px;
                margin-bottom: 10px;
            }
            .presentation{
                width: 100%;
                text-align: center;

                font-size: 20px;
                padding-top: 50px;
            }
        }
    </style>
    <header >
        <nav class="navbar" >
            <div class="max-width">
                <div class="logo">
                    <a href="#">Peak <span> </span><span>EXPLORER.</span></a>
                </div>
                <ul class="menu">
                    <li><a href="{{ path('app_index') }}" class="menu-btn">Acceuil</a></li>
                    <li><a href="{{ path('app_login') }}" class="menu-btn">login</a></li>
                    <li><a href="{{ path('app_Domaine') }}" class="menu-btn">Domaine</a></li>
                    <li><a href="{{ path('app_register') }}" class="menu-btn">Register</a></li>
                    <li><a href="{{ path('admin_domaine') }}" class="menu-btn">Admin</a></li>

                </ul>
                <div class="menu-btn">
                    <i class="fas fa-bars"></i>
                    <img src="public/assets/images/menu.png">
                </div>
            </div>
        </nav>
    </header>
    <br><br><br><br>
    <div class="presentation">    <h1>les Stations de skis</h1>
    <p>Bienvenue sur la page d'édition des stations de ski,
        <br>Vous pourrez ici ajouter, modifier ou supprimer des stations de ski.
        et aussi ouvrir/fermé les stations de ski en fonction de l'heure actuelle.
    </p>
    </div>
    <br>
    <br>

    <button><a class="acces" href="{{ path('app_stationski_type' , {'id' : id}) }}">Ajouter une station</a></button>
    <div class="global">
    {% for stations in station  %}
        <div class="Domaine">
            <h3>{{ stations.name }}</h3>

            <img src="/uploads/{{ stations.image }}" alt="image de la station" width="200" height="200">
            <br>
            <a class="acces" href="{{ path('station_edit', {'id': stations.id}) }}">voir la station</a>
        </div>

    {% endfor %}
    </div>
    <button><a class="acces" href="{{ path('app_auto' , {'id' : id})}}">Ouvrir les station</a></button>
{% endblock %}

templates/app/fdomaine.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AppController!{% endblock %}

{% block body %}
    <style>
        .navbar{
            padding: 15px 0;
            background: #03312E;
        }
        .navbar .logo a span{
            color: #F0F6F6;
            transition: all 0.3s ease;
        }
        body {
            background-image: url('/assets/image/background.png');
            background-size: cover;
            background-repeat: no-repeat;
        }
        form {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            max-width: 400px;
            margin: 150px auto 0 auto;
        }
        input[type="text"],
        input[type="email"],
        input[type="password"] {
            display: block;
            width: 95%;
            padding: 10px;
            margin-bottom: 20px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-family: sans-serif;
            color: #333;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        }
        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-family: sans-serif;
            cursor: pointer;
        }
        .bodys{
            padding-top : 110px;
            height: auto;
        }
    </style>

    <div class="body">
        <header >
            <nav class="navbar" >
                <div class="max-width">
                    <div class="logo">
                        <a href="#">Peak <span> </span><span>EXPLORER.</span></a>
                    </div>
                    <ul class="menu">
                        <li><a href="{{ path('app_index') }}" class="menu-btn">acceuil</a></li>
                        <li><a href="{{ path('admin_domaine') }}" class="menu-btn">Stations</a></li>
                        <li><a href="{{ path('app_login') }}" class="menu-btn">login</a></li>
                        <li><a href="{{ path('app_register') }}" class="menu-btn">Register</a></li>
                        <li><a href="{{ path('app_Domaine') }}" class="menu-btn">Domaine</a></li>

                    </ul>
                    <div class="menu-btn">
                        <i class="fas fa-bars"></i>
                        <img src="public/assets/images/menu.png">
                    </div>
                </div>
            </nav>
        </header>
        <br><br><br><br>
    <h1>les Domaines de skis</h1>
    <p>
        Bienvenue sur la page des domaines de skis
    </p>
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.image) }}
    {{ form_end(form) }}

    </div>
{% endblock %}

templates/app/fremontee.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AppController!{% endblock %}

{% block body %}
    <style>
        .navbar{
            padding: 15px 0;
            background: #03312E;
        }
        .navbar .logo a span{
            color: #F0F6F6;
            transition: all 0.3s ease;
        }
        body {
            background-image: url('/assets/image/background.png');
            background-size: cover;
            background-repeat: no-repeat;
        }
        .form {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            max-width: 400px;
            margin: 150px auto 0 auto;
            margin-top:20px;
        }
        input[type="text"],
        input[type="email"],
        input[type="password"] {
            display: block;
            width: 95%;
            padding: 10px;
            margin-bottom: 20px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-family: sans-serif;
            color: #333;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        }
        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-family: sans-serif;
            cursor: pointer;

        }
        .form{
            height: 200px;
        }
    </style>
<header >
    <nav class="navbar" >
        <div class="max-width">
            <div class="logo">
                <a href="#">Peak <span> </span><span>EXPLORER.</span></a>
            </div>
            <ul class="menu">
                <li><a href="{{ path('app_index') }}" class="menu-btn">acceuil</a></li>
                <li><a href="{{ path('admin_domaine') }}" class="menu-btn">Stations</a></li>
                <li><a href="{{ path('app_login') }}" class="menu-btn">login</a></li>
                <li><a href="{{ path('app_register') }}" class="menu-btn">Register</a></li>
                <li><a href="{{ path('app_Domaine') }}" class="menu-btn">Domaine</a></li>

            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
                <img src="public/assets/images/menu.png">
            </div>
        </div>
    </nav>
</header>
 <br><br><br><br>
    <h1>Ajouter des pistes ou des remontées</h1>
    <div class="form">
        <h3> Ajout de pistes</h3>
        <form method="post" action="{{ path('add_pistes' , {id: id}) }}">
            <label for="name">Nom de la piste</label>
            <input name="name" type="text">
            <label for="name">Difficulté</label>
            <input name="difficulte" type="text">
            <input name="submit" type="submit" value="Envoyer">

        </form>
    </div >
    <div class="form">
        <h3> Ajout de remontées</h3>
        <form method="post" action="{{ path('add_remontees' , {id: id}) }}">
            <label for="name">Nom de la remontée</label>
            <input name="name" type="text">
            <input name="submit" type="submit" value="Envoyer">

        </form>


{% endblock %}